apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Warehouse
    uid: warehouse
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    user: ${WAREHOUSE_USER}
    jsonData:
      database: warehouse
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${WAREHOUSE_PASSWORD}
